import { Inter } from "next/font/google";
import "./globals.css";
import NavBarComponent from "@/components/NavBarComponent";
import NavbarComponent from "@/components/NavBarComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavbarComponent/>
        {children}</body>
    </html>
  );
}
